apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-server-dab-p2-13448cc8-f1cc-42a8-ae1a-c56d1edda206
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-server-dab-p2-13448cc8-f1cc-42a8-ae1a-c56d1edda206
  template:
    metadata:
      labels:
        app: database-server-dab-p2-13448cc8-f1cc-42a8-ae1a-c56d1edda206
    spec:
      containers:
      - name: database-server-dab-p2-13448cc8-f1cc-42a8-ae1a-c56d1edda206
        image: postgres:14.1
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: project-env
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: database-server-dab-p2-13448cc8-f1cc-42a8-ae1a-c56d1edda206
spec:
  selector:
    app: database-server-dab-p2-13448cc8-f1cc-42a8-ae1a-c56d1edda206
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
